/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomComponents;

import java.awt.Color;
import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.GridBagLayout;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.util.Arrays;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.plaf.basic.BasicComboBoxRenderer;
import javax.swing.text.StyledEditorKit;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Vin
 */
public final class AdvancedFormatToolBar extends javax.swing.JPanel {

    protected UndoManager undo = new UndoManager();
    UndoAction undoAction = new UndoAction();
    RedoAction redoAction = new RedoAction();
    Color forcegroundColor = Color.black;
    JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
   
    /**
     * Creates new form AdvancedFormatToolBar
     */
    public AdvancedFormatToolBar() {
        initComponents();
      
        initFontComboBox();
        FontSize.setAction(new StyledEditorKit.FontSizeAction(FontSize.getActionCommand(), Integer.parseInt(FontSize.getSelectedItem().toString())));
        FontChooser.setAction(new StyledEditorKit.FontFamilyAction(FontChooser.getActionCommand(), FontChooser.getSelectedItem().toString()));
    }

    public void setTextEditor(StyledTextEditor editor){
        textEditor = editor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jToolBar1 = new javax.swing.JToolBar();
        btnSaveDocument = new javax.swing.JButton();
        btnSaveAsDocument = new javax.swing.JButton();
        btnOpenDocument = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        btnBold = new javax.swing.JButton();
        btnItalic = new javax.swing.JButton();
        btnUnderline = new javax.swing.JButton();
        FontChooser = new javax.swing.JComboBox();
        FontSize = new javax.swing.JComboBox();
        btnInsertImage = new javax.swing.JButton();
        btnColorChooser = new javax.swing.JButton();
        btnLeftAlign = new javax.swing.JButton();
        btnCenterAlign = new javax.swing.JButton();
        btnRightAlign = new javax.swing.JButton();
        btnJustifyAlign = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 30));
        setMinimumSize(new java.awt.Dimension(600, 30));
        setPreferredSize(new java.awt.Dimension(609, 30));

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setDoubleBuffered(true);
        jToolBar1.setMargin(new java.awt.Insets(0, 2, 0, 2));
        jToolBar1.setMaximumSize(new java.awt.Dimension(505, 30));
        jToolBar1.setMinimumSize(new java.awt.Dimension(215, 30));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 30));

        btnSaveDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSaveDocument.setToolTipText("Save");
        btnSaveDocument.setFocusable(false);
        btnSaveDocument.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveDocument.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDocumentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaveDocument);

        btnSaveAsDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_as.png"))); // NOI18N
        btnSaveAsDocument.setToolTipText("Save As...");
        btnSaveAsDocument.setFocusable(false);
        btnSaveAsDocument.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveAsDocument.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveAsDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsDocumentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaveAsDocument);

        btnOpenDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        btnOpenDocument.setToolTipText("Open");
        btnOpenDocument.setFocusable(false);
        btnOpenDocument.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDocument.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpenDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDocumentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpenDocument);

        btnUndo.setAction(undoAction);
        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow_undo.png"))); // NOI18N
        btnUndo.setToolTipText("Undo");
        btnUndo.setFocusable(false);
        btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUndo);

        btnRedo.setAction(redoAction);
        btnRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow_redo.png"))); // NOI18N
        btnRedo.setToolTipText("Redo");
        btnRedo.setFocusable(false);
        btnRedo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRedo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRedo);

        btnBold.setAction(new StyledEditorKit.BoldAction());
        btnBold.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bold.png"))); // NOI18N
        btnBold.setText("");
        btnBold.setToolTipText("Bold");
        btnBold.setFocusable(false);
        btnBold.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBold.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoldActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBold);

        btnItalic.setAction(new StyledEditorKit.ItalicAction());
        btnItalic.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnItalic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/italic.png"))); // NOI18N
        btnItalic.setText("");
        btnItalic.setToolTipText("Italic");
        btnItalic.setFocusable(false);
        btnItalic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnItalic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnBold, org.jdesktop.beansbinding.ELProperty.create("${border}"), btnItalic, org.jdesktop.beansbinding.BeanProperty.create("border"));
        bindingGroup.addBinding(binding);

        jToolBar1.add(btnItalic);

        btnUnderline.setAction(new StyledEditorKit.UnderlineAction());
        btnUnderline.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/underline.png"))); // NOI18N
        btnUnderline.setText("");
        btnUnderline.setToolTipText("Underline");
        btnUnderline.setFocusable(false);
        btnUnderline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnderline.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnUnderline);

        FontChooser.setEditable(true);
        FontChooser.setFocusable(false);
        FontChooser.setInheritsPopupMenu(true);
        FontChooser.setMaximumSize(new java.awt.Dimension(300, 30));
        FontChooser.setMinimumSize(new java.awt.Dimension(100, 30));
        FontChooser.setPreferredSize(new java.awt.Dimension(90, 30));
        FontChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FontChooserActionPerformed(evt);
            }
        });
        jToolBar1.add(FontChooser);

        FontSize.setEditable(true);
        FontSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "6", "7", "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "28", "36", "42", " " }));
        FontSize.setSelectedIndex(7);
        FontSize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FontSize.setDoubleBuffered(true);
        FontSize.setFocusable(false);
        FontSize.setInheritsPopupMenu(true);
        FontSize.setMaximumSize(new java.awt.Dimension(50, 30));
        FontSize.setPreferredSize(new java.awt.Dimension(40, 30));
        FontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FontSizeActionPerformed(evt);
            }
        });
        jToolBar1.add(FontSize);

        btnInsertImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert_image.png"))); // NOI18N
        btnInsertImage.setToolTipText("");
        btnInsertImage.setFocusable(false);
        btnInsertImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertImage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInsertImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertImageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInsertImage);

        btnColorChooser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnColorChooser.setText("A");
        btnColorChooser.setFocusable(false);
        btnColorChooser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColorChooser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorChooserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnColorChooser);

        btnLeftAlign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_align.png"))); // NOI18N
        btnLeftAlign.setFocusable(false);
        btnLeftAlign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLeftAlign.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLeftAlign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftAlignActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLeftAlign);

        btnCenterAlign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/center_align.png"))); // NOI18N
        btnCenterAlign.setFocusable(false);
        btnCenterAlign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCenterAlign.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCenterAlign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenterAlignActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCenterAlign);

        btnRightAlign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right_align.png"))); // NOI18N
        btnRightAlign.setFocusable(false);
        btnRightAlign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRightAlign.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRightAlign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightAlignActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRightAlign);

        btnJustifyAlign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/justify_align.png"))); // NOI18N
        btnJustifyAlign.setToolTipText("Justify");
        btnJustifyAlign.setFocusable(false);
        btnJustifyAlign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJustifyAlign.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJustifyAlign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJustifyAlignActionPerformed(evt);
            }
        });
        jToolBar1.add(btnJustifyAlign);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBoldActionPerformed

    private void btnColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorChooserActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Chọn màu chữ", forcegroundColor);
        if (color != null) {
            forcegroundColor = color;
            btnColorChooser.setForeground(color);
            (new StyledEditorKit.ForegroundAction("Color", color)).actionPerformed(evt);
        }
    }//GEN-LAST:event_btnColorChooserActionPerformed

    private void FontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FontSizeActionPerformed
        // TODO add your handling code here:
        (new StyledEditorKit.FontSizeAction(FontSize.getActionCommand(), Integer.parseInt(FontSize.getSelectedItem().toString()))).actionPerformed(evt);
          
    }//GEN-LAST:event_FontSizeActionPerformed

    private void FontChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FontChooserActionPerformed
        // TODO add your handling code here:
        (new StyledEditorKit.FontFamilyAction(FontChooser.getActionCommand(), FontChooser.getSelectedItem().toString())).actionPerformed(evt);
    }//GEN-LAST:event_FontChooserActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnSaveAsDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsDocumentActionPerformed
        // TODO add your handling code here:
        textEditor.SaveAsDocument();
        
        topFrame.setTitle(textEditor.currentFile.getAbsolutePath());
    }//GEN-LAST:event_btnSaveAsDocumentActionPerformed

    private void btnSaveDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDocumentActionPerformed
        // TODO add your handling code here:
        textEditor.SaveDocument();
        topFrame.setTitle(textEditor.currentFile.getAbsolutePath());
    }//GEN-LAST:event_btnSaveDocumentActionPerformed

    private void btnOpenDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDocumentActionPerformed
        // TODO add your handling code here:
        textEditor.OpenDocument();
        topFrame.setTitle(textEditor.currentFile.getAbsolutePath());
    }//GEN-LAST:event_btnOpenDocumentActionPerformed

    private void btnLeftAlignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftAlignActionPerformed
        // TODO add your handling code here:
        (new StyledEditorKit.AlignmentAction(btnLeftAlign.getActionCommand(), 0)).actionPerformed(evt);
    }//GEN-LAST:event_btnLeftAlignActionPerformed

    private void btnCenterAlignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenterAlignActionPerformed
        // TODO add your handling code here:
          (new StyledEditorKit.AlignmentAction(btnCenterAlign.getActionCommand(), 1)).actionPerformed(evt);
    }//GEN-LAST:event_btnCenterAlignActionPerformed

    private void btnRightAlignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightAlignActionPerformed
        // TODO add your handling code here:
          (new StyledEditorKit.AlignmentAction(btnRightAlign.getActionCommand(), 2)).actionPerformed(evt);
    }//GEN-LAST:event_btnRightAlignActionPerformed

    private void btnJustifyAlignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJustifyAlignActionPerformed
        // TODO add your handling code here:
        (new StyledEditorKit.AlignmentAction(btnJustifyAlign.getActionCommand(), 3)).actionPerformed(evt);
    }//GEN-LAST:event_btnJustifyAlignActionPerformed

    private void btnInsertImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertImageActionPerformed
        // TODO add your handling code here:
        textEditor.InsertImage();
    }//GEN-LAST:event_btnInsertImageActionPerformed

    public void initFontComboBox() {
        List<String> fonts = Arrays.asList(GraphicsEnvironment
                .getLocalGraphicsEnvironment()
                .getAvailableFontFamilyNames());
        fonts.forEach(FontChooser::addItem);
        FontChooser.setRenderer(new ComboRenderer(FontChooser));
        FontChooser.setSelectedItem("Times New Roman");
    }
    private StyledTextEditor textEditor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FontChooser;
    private javax.swing.JComboBox FontSize;
    private javax.swing.JButton btnBold;
    private javax.swing.JButton btnCenterAlign;
    private javax.swing.JButton btnColorChooser;
    private javax.swing.JButton btnInsertImage;
    private javax.swing.JButton btnItalic;
    private javax.swing.JButton btnJustifyAlign;
    private javax.swing.JButton btnLeftAlign;
    private javax.swing.JButton btnOpenDocument;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnRightAlign;
    private javax.swing.JButton btnSaveAsDocument;
    private javax.swing.JButton btnSaveDocument;
    private javax.swing.JButton btnUnderline;
    private javax.swing.JButton btnUndo;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public UndoableEditListener getUndoableEditLitener() {
        return new MyUndoableEditListener();
    }


     class UndoAction extends AbstractAction {

        public UndoAction() {
            super();
            setEnabled(false);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                undo.undo();
            } catch (CannotUndoException ex) {
                System.out.println("Unable to undo: " + ex);
            }
            updateUndoState();
            redoAction.updateRedoState();
        }

        protected void updateUndoState() {
            if (undo.canUndo()) {
                setEnabled(true);
               // putValue(Action.NAME, undo.getUndoPresentationName());
            } else {
                setEnabled(false);
              //  putValue(Action.NAME, "Undo");
            }
        }
    }

    class RedoAction extends AbstractAction {

        public RedoAction() {
            super();
            setEnabled(false);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                undo.redo();
            } catch (CannotRedoException ex) {
                System.out.println("Unable to redo: " + ex);
            }
            updateRedoState();
            undoAction.updateUndoState();
        }

        protected void updateRedoState() {
            if (undo.canRedo()) {
                setEnabled(true);
              //  putValue(Action.NAME, undo.getRedoPresentationName());
            } else {
                setEnabled(false);
               // putValue(Action.NAME, "Redo");
            }
        }
    }

    //This one listens for edits that can be undone.

    protected class MyUndoableEditListener
            implements UndoableEditListener {

        @Override
        public void undoableEditHappened(UndoableEditEvent e) {
            //Remember the edit and update the menus.
            undo.addEdit(e.getEdit());
            undoAction.updateUndoState();
            redoAction.updateRedoState();
        }
    }
    
}

class ComboRenderer extends BasicComboBoxRenderer {

    private static final long serialVersionUID = 1L;
    private final JComboBox comboBox;
    final DefaultListCellRenderer defaultRenderer = new DefaultListCellRenderer();
    private int row;

    ComboRenderer(JComboBox fontsBox) {
        comboBox = fontsBox;
    }

    private void manItemInCombo() {
        if (comboBox.getItemCount() > 0) {
            final Object comp = comboBox.getUI().getAccessibleChild(comboBox, 0);
            if ((comp instanceof JPopupMenu)) {
                final JList list = new JList(comboBox.getModel());
                final JPopupMenu popup = (JPopupMenu) comp;
                final JScrollPane scrollPane = (JScrollPane) popup.getComponent(0);
                final JViewport viewport = scrollPane.getViewport();
                final Rectangle rect = popup.getVisibleRect();
                final Point pt = viewport.getViewPosition();
                row = list.locationToIndex(pt);
            }
        }
    }

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (list.getModel().getSize() > 0) {
            manItemInCombo();
        }
        final JLabel renderer = (JLabel) defaultRenderer.getListCellRendererComponent(list, value, row, isSelected, cellHasFocus);
        final Object fntObj = value;
        final String fontFamilyName = (String) fntObj;
        setFont(new java.awt.Font(fontFamilyName, java.awt.Font.PLAIN, 16));
        return this;
    }  
}

